version: 2

jobs:
  build:
    docker:
      - image: undefinedref/fast_api_primary:0.0.1
        auth:
          username: undefinedref
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: TEST
          command: |
            cd app
            python3 -m pytest test.py